- hosts: all
  tags: always
  become: true

  pre_tasks:
    - name: update and upgrade packages
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 86400 
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
  

- hosts: all
  tags: all
  become: true
  roles: 
    - all

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation
